Making the project easier to build
...yes, NAMESPACE was generated by a tool. *sigh*

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,28 +1,15 @@
 #!/bin/sh
 
-# compileAttributes requires a NAMESPACE file, which is generated by
-# roxygen. Roxygen will not generate all of the documentation until we
-# run compileAttributes (to generate RcppExports.R). Therefore, we run
-# roxygenise to generate the (incomplete!) NAMESPACE file, run
-# compile_attributes(), and then run roxygenise again.
-function roxygenise() {
-    Rscript -e "roxygen2::roxygenize()"
-    if [ $? -ne 0 ]
-    then
-        echo "Error: Failed to create documentation"
-        exit 1
-    fi
-}
+Rscript -e "Rcpp::compileAttributes()"
+if [ $? -ne 0 ]
+then
+    echo "Error: Failed to compile attributes"
+    exit 1
+fi
 
-function compile_attributes() {
-    Rscript -e "Rcpp::compileAttributes()"
-    if [ $? -ne 0 ]
-    then
-        echo "Error: Failed to compile attributes"
-        exit 1
-    fi
-}
-
-roxygenise
-compile_attributes
-roxygenise
+Rscript -e "roxygen2::roxygenize()"
+if [ $? -ne 0 ]
+then
+    echo "Error: Failed to create documentation"
+    exit 1
+fi
